from aiogram.dispatcher.filters.state import StatesGroup, State


class Steps(StatesGroup):
    name_surname = State()
    phone_number = State()
    get_email = State()
    get_education = State()
    get_tech_skills = State()
    get_soft_skills = State()
    get_projects = State()
    get_lang = State()
    get_lang_level = State()
    get_country = State()
    get_city = State()
    get_profession = State()
    get_description = State()
    get_work_experience = State()
    get_job_description = State()
    get_how_long = State()
    end_message = State()
    name_surname_edit = State()
    phone_number_edit = State()
    get_email_edit = State()
    get_education_edit = State()
    get_tech_skills_edit = State()
    get_soft_skills_edit = State()
    get_projects_edit = State()
    get_lang_edit = State()
    get_lang_level_edit = State()
    get_country_edit = State()
    get_city_edit = State()
    get_profession_edit = State()
    get_description_edit = State()
    get_work_experience_edit = State()
    get_job_description_edit = State()
    get_how_long_edit = State()
    end_message_edit = State()

